In [7]:
import numpy as np


In [9]:
arr = np.array([10,20,30,40])
arr

array([10, 20, 30, 40])

In [10]:
type(arr)

numpy.ndarray

In [11]:
arr1 = np.array([10,3.14])
arr1

array([10.  ,  3.14])

In [14]:
arr2 = np.array([10,3.14,'a'])
arr2

array(['10', '3.14', 'a'], dtype='<U32')

In [15]:
arr3 = np.array([[10,20,30],[40,50,60],[70,80,90]])
arr3

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [16]:
arr3.ndim

2

In [17]:
arr3.shape

(3, 3)

In [19]:
arr2= np.arange(1,13).reshape((3,4))
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [20]:
arr2[0,1]

2

In [21]:
type(arr2)

numpy.ndarray

In [22]:
arr2[0,1],arr2[1,3]

(2, 8)

In [28]:
arr3= np.arange(1,25).reshape((2,4,3))
arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

In [29]:
arr3[0,2,0]

7

In [30]:
arr3[0,2,1],arr3[0,1,0],arr3[1,2,0],arr3[1,2,1]

(8, 4, 19, 20)

In [32]:
arr4 = np.arange(1,31).reshape((6,5))
arr4

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [33]:
arr[1:5]

array([20, 30, 40])

In [34]:
arr4[:]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [35]:
arr4[ : , 1:4]

array([[ 2,  3,  4],
       [ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19],
       [22, 23, 24],
       [27, 28, 29]])

In [36]:
arr4[1:5,1:4]

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19],
       [22, 23, 24]])